// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.27.3
// source: expression/types.proto

package expression

import (
	"fmt"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddrType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Transport string `protobuf:"bytes,1,opt,name=transport,proto3" json:"transport,omitempty"`
	Addr      string `protobuf:"bytes,2,opt,name=addr,proto3" json:"addr,omitempty"`
	Port      string `protobuf:"bytes,3,opt,name=port,proto3" json:"port,omitempty"`
}

func (x *AddrType) Reset() {
	*x = AddrType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_expression_types_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddrType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddrType) ProtoMessage() {}

func (x *AddrType) ProtoReflect() protoreflect.Message {
	mi := &file_expression_types_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddrType.ProtoReflect.Descriptor instead.
func (*AddrType) Descriptor() ([]byte, []int) {
	return file_expression_types_proto_rawDescGZIP(), []int{0}
}

func (x *AddrType) GetTransport() string {
	if x != nil {
		return x.Transport
	}
	return ""
}

func (x *AddrType) GetAddr() string {
	if x != nil {
		return x.Addr
	}
	return ""
}

func (x *AddrType) GetPort() string {
	if x != nil {
		return x.Port
	}
	return ""
}

type ConnType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Source      *AddrType `protobuf:"bytes,1,opt,name=source,proto3" json:"source,omitempty"`
	Destination *AddrType `protobuf:"bytes,2,opt,name=destination,proto3" json:"destination,omitempty"`
}

func (x *ConnType) Reset() {
	*x = ConnType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_expression_types_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConnType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConnType) ProtoMessage() {}

func (x *ConnType) ProtoReflect() protoreflect.Message {
	mi := &file_expression_types_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConnType.ProtoReflect.Descriptor instead.
func (*ConnType) Descriptor() ([]byte, []int) {
	return file_expression_types_proto_rawDescGZIP(), []int{1}
}

func (x *ConnType) GetSource() *AddrType {
	if x != nil {
		return x.Source
	}
	return nil
}

func (x *ConnType) GetDestination() *AddrType {
	if x != nil {
		return x.Destination
	}
	return nil
}

type UrlType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Scheme   string `protobuf:"bytes,1,opt,name=scheme,proto3" json:"scheme,omitempty"`
	Domain   string `protobuf:"bytes,2,opt,name=domain,proto3" json:"domain,omitempty"`
	Host     string `protobuf:"bytes,3,opt,name=host,proto3" json:"host,omitempty"`
	Port     string `protobuf:"bytes,4,opt,name=port,proto3" json:"port,omitempty"`
	Path     string `protobuf:"bytes,5,opt,name=path,proto3" json:"path,omitempty"`
	Query    string `protobuf:"bytes,6,opt,name=query,proto3" json:"query,omitempty"`
	Fragment string `protobuf:"bytes,7,opt,name=fragment,proto3" json:"fragment,omitempty"`
}

func (x *UrlType) Reset() {
	*x = UrlType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_expression_types_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UrlType) String() string {
	s := fmt.Sprintf("%s://%s%s", x.Scheme, x.Host, x.Path)
	if x.Query != "" {
		s += "?" + x.Query
	}
	if x.Fragment != "" {
		s += "#" + x.Fragment
	}
	return s
}

func (*UrlType) ProtoMessage() {}

func (x *UrlType) ProtoReflect() protoreflect.Message {
	mi := &file_expression_types_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UrlType.ProtoReflect.Descriptor instead.
func (*UrlType) Descriptor() ([]byte, []int) {
	return file_expression_types_proto_rawDescGZIP(), []int{2}
}

func (x *UrlType) GetScheme() string {
	if x != nil {
		return x.Scheme
	}
	return ""
}

func (x *UrlType) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *UrlType) GetHost() string {
	if x != nil {
		return x.Host
	}
	return ""
}

func (x *UrlType) GetPort() string {
	if x != nil {
		return x.Port
	}
	return ""
}

func (x *UrlType) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *UrlType) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *UrlType) GetFragment() string {
	if x != nil {
		return x.Fragment
	}
	return ""
}

type NetworkRequestType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Raw []byte `protobuf:"bytes,1,opt,name=raw,proto3" json:"raw,omitempty"`
}

func (x *NetworkRequestType) Reset() {
	*x = NetworkRequestType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_expression_types_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NetworkRequestType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkRequestType) ProtoMessage() {}

func (x *NetworkRequestType) ProtoReflect() protoreflect.Message {
	mi := &file_expression_types_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkRequestType.ProtoReflect.Descriptor instead.
func (*NetworkRequestType) Descriptor() ([]byte, []int) {
	return file_expression_types_proto_rawDescGZIP(), []int{3}
}

func (x *NetworkRequestType) GetRaw() []byte {
	if x != nil {
		return x.Raw
	}
	return nil
}

type NetworkResponseType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Conn *ConnType `protobuf:"bytes,1,opt,name=conn,proto3" json:"conn,omitempty"`
	Raw  []byte    `protobuf:"bytes,2,opt,name=raw,proto3" json:"raw,omitempty"`
}

func (x *NetworkResponseType) Reset() {
	*x = NetworkResponseType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_expression_types_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NetworkResponseType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NetworkResponseType) ProtoMessage() {}

func (x *NetworkResponseType) ProtoReflect() protoreflect.Message {
	mi := &file_expression_types_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NetworkResponseType.ProtoReflect.Descriptor instead.
func (*NetworkResponseType) Descriptor() ([]byte, []int) {
	return file_expression_types_proto_rawDescGZIP(), []int{4}
}

func (x *NetworkResponseType) GetConn() *ConnType {
	if x != nil {
		return x.Conn
	}
	return nil
}

func (x *NetworkResponseType) GetRaw() []byte {
	if x != nil {
		return x.Raw
	}
	return nil
}

type SshRequestType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Raw []byte `protobuf:"bytes,1,opt,name=raw,proto3" json:"raw,omitempty"`
}

func (x *SshRequestType) Reset() {
	*x = SshRequestType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_expression_types_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SshRequestType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SshRequestType) ProtoMessage() {}

func (x *SshRequestType) ProtoReflect() protoreflect.Message {
	mi := &file_expression_types_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SshRequestType.ProtoReflect.Descriptor instead.
func (*SshRequestType) Descriptor() ([]byte, []int) {
	return file_expression_types_proto_rawDescGZIP(), []int{5}
}

func (x *SshRequestType) GetRaw() []byte {
	if x != nil {
		return x.Raw
	}
	return nil
}

type SshResponseType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Conn     *ConnType         `protobuf:"bytes,1,opt,name=conn,proto3" json:"conn,omitempty"`
	Raw      []byte            `protobuf:"bytes,2,opt,name=raw,proto3" json:"raw,omitempty"`
	Metadata map[string]string `protobuf:"bytes,3,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *SshResponseType) Reset() {
	*x = SshResponseType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_expression_types_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SshResponseType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SshResponseType) ProtoMessage() {}

func (x *SshResponseType) ProtoReflect() protoreflect.Message {
	mi := &file_expression_types_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SshResponseType.ProtoReflect.Descriptor instead.
func (*SshResponseType) Descriptor() ([]byte, []int) {
	return file_expression_types_proto_rawDescGZIP(), []int{6}
}

func (x *SshResponseType) GetConn() *ConnType {
	if x != nil {
		return x.Conn
	}
	return nil
}

func (x *SshResponseType) GetRaw() []byte {
	if x != nil {
		return x.Raw
	}
	return nil
}

func (x *SshResponseType) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type HTTPRequestType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url         *UrlType          `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Method      string            `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	Headers     map[string]string `protobuf:"bytes,3,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	ContentType string            `protobuf:"bytes,4,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Body        []byte            `protobuf:"bytes,5,opt,name=body,proto3" json:"body,omitempty"`
	Raw         []byte            `protobuf:"bytes,6,opt,name=raw,proto3" json:"raw,omitempty"`
}

func (x *HTTPRequestType) Reset() {
	*x = HTTPRequestType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_expression_types_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HTTPRequestType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HTTPRequestType) ProtoMessage() {}

func (x *HTTPRequestType) ProtoReflect() protoreflect.Message {
	mi := &file_expression_types_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HTTPRequestType.ProtoReflect.Descriptor instead.
func (*HTTPRequestType) Descriptor() ([]byte, []int) {
	return file_expression_types_proto_rawDescGZIP(), []int{7}
}

func (x *HTTPRequestType) GetUrl() *UrlType {
	if x != nil {
		return x.Url
	}
	return nil
}

func (x *HTTPRequestType) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *HTTPRequestType) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *HTTPRequestType) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *HTTPRequestType) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *HTTPRequestType) GetRaw() []byte {
	if x != nil {
		return x.Raw
	}
	return nil
}

type HTTPResponseType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url         *UrlType          `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Status      int32             `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Body        []byte            `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	BodyString  string            `protobuf:"bytes,4,opt,name=body_string,json=bodyString,proto3" json:"body_string,omitempty"`
	Headers     map[string]string `protobuf:"bytes,5,rep,name=headers,proto3" json:"headers,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	ContentType string            `protobuf:"bytes,6,opt,name=content_type,json=contentType,proto3" json:"content_type,omitempty"`
	Latency     int32             `protobuf:"varint,7,opt,name=latency,proto3" json:"latency,omitempty"`
	Raw         []byte            `protobuf:"bytes,8,opt,name=raw,proto3" json:"raw,omitempty"`
	Title       string            `protobuf:"bytes,9,opt,name=title,proto3" json:"title,omitempty"`
	TitleString string            `protobuf:"bytes,10,opt,name=title_string,json=titleString,proto3" json:"title_string,omitempty"`
	RawHeader   []byte            `protobuf:"bytes,11,opt,name=raw_header,json=rawHeader,proto3" json:"raw_header,omitempty"`
	RawCert     []byte            `protobuf:"bytes,12,opt,name=raw_cert,json=rawCert,proto3" json:"raw_cert,omitempty"`
	IconUrl     string            `protobuf:"bytes,13,opt,name=icon_url,json=iconUrl,proto3" json:"icon_url,omitempty"`
}

func (x *HTTPResponseType) Reset() {
	*x = HTTPResponseType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_expression_types_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HTTPResponseType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HTTPResponseType) ProtoMessage() {}

func (x *HTTPResponseType) ProtoReflect() protoreflect.Message {
	mi := &file_expression_types_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HTTPResponseType.ProtoReflect.Descriptor instead.
func (*HTTPResponseType) Descriptor() ([]byte, []int) {
	return file_expression_types_proto_rawDescGZIP(), []int{8}
}

func (x *HTTPResponseType) GetUrl() *UrlType {
	if x != nil {
		return x.Url
	}
	return nil
}

func (x *HTTPResponseType) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *HTTPResponseType) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

func (x *HTTPResponseType) GetBodyString() string {
	if x != nil {
		return x.BodyString
	}
	return ""
}

func (x *HTTPResponseType) GetHeaders() map[string]string {
	if x != nil {
		return x.Headers
	}
	return nil
}

func (x *HTTPResponseType) GetContentType() string {
	if x != nil {
		return x.ContentType
	}
	return ""
}

func (x *HTTPResponseType) GetLatency() int32 {
	if x != nil {
		return x.Latency
	}
	return 0
}

func (x *HTTPResponseType) GetRaw() []byte {
	if x != nil {
		return x.Raw
	}
	return nil
}

func (x *HTTPResponseType) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *HTTPResponseType) GetTitleString() string {
	if x != nil {
		return x.TitleString
	}
	return ""
}

func (x *HTTPResponseType) GetRawHeader() []byte {
	if x != nil {
		return x.RawHeader
	}
	return nil
}

func (x *HTTPResponseType) GetRawCert() []byte {
	if x != nil {
		return x.RawCert
	}
	return nil
}

func (x *HTTPResponseType) GetIconUrl() string {
	if x != nil {
		return x.IconUrl
	}
	return ""
}

type ReverseType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url                *UrlType `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Rmi                string   `protobuf:"bytes,2,opt,name=rmi,proto3" json:"rmi,omitempty"`
	Ldap               string   `protobuf:"bytes,3,opt,name=ldap,proto3" json:"ldap,omitempty"`
	Flag               string   `protobuf:"bytes,4,opt,name=flag,proto3" json:"flag,omitempty"`
	Domain             string   `protobuf:"bytes,5,opt,name=domain,proto3" json:"domain,omitempty"`
	Ip                 string   `protobuf:"bytes,6,opt,name=ip,proto3" json:"ip,omitempty"`
	IsDomainNameServer bool     `protobuf:"varint,7,opt,name=is_domain_name_server,json=isDomainNameServer,proto3" json:"is_domain_name_server,omitempty"`
	GroupId            string   `protobuf:"bytes,8,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
}

func (x *ReverseType) Reset() {
	*x = ReverseType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_expression_types_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReverseType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReverseType) ProtoMessage() {}

func (x *ReverseType) ProtoReflect() protoreflect.Message {
	mi := &file_expression_types_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReverseType.ProtoReflect.Descriptor instead.
func (*ReverseType) Descriptor() ([]byte, []int) {
	return file_expression_types_proto_rawDescGZIP(), []int{9}
}

func (x *ReverseType) GetUrl() *UrlType {
	if x != nil {
		return x.Url
	}
	return nil
}

func (x *ReverseType) GetRmi() string {
	if x != nil {
		return x.Rmi
	}
	return ""
}

func (x *ReverseType) GetLdap() string {
	if x != nil {
		return x.Ldap
	}
	return ""
}

func (x *ReverseType) GetFlag() string {
	if x != nil {
		return x.Flag
	}
	return ""
}

func (x *ReverseType) GetDomain() string {
	if x != nil {
		return x.Domain
	}
	return ""
}

func (x *ReverseType) GetIp() string {
	if x != nil {
		return x.Ip
	}
	return ""
}

func (x *ReverseType) GetIsDomainNameServer() bool {
	if x != nil {
		return x.IsDomainNameServer
	}
	return false
}

func (x *ReverseType) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

type OOB struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Filter       string `protobuf:"bytes,1,opt,name=Filter,proto3" json:"Filter,omitempty"`
	HTTP         string `protobuf:"bytes,2,opt,name=HTTP,proto3" json:"HTTP,omitempty"`
	DNS          string `protobuf:"bytes,3,opt,name=DNS,proto3" json:"DNS,omitempty"`
	ProtocolHTTP string `protobuf:"bytes,4,opt,name=ProtocolHTTP,proto3" json:"ProtocolHTTP,omitempty"` // 默认值 "http"
	ProtocolDNS  string `protobuf:"bytes,5,opt,name=ProtocolDNS,proto3" json:"ProtocolDNS,omitempty"`   // 默认值 "dns"
}

func (x *OOB) Reset() {
	*x = OOB{}
	if protoimpl.UnsafeEnabled {
		mi := &file_expression_types_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *OOB) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OOB) ProtoMessage() {}

func (x *OOB) ProtoReflect() protoreflect.Message {
	mi := &file_expression_types_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OOB.ProtoReflect.Descriptor instead.
func (*OOB) Descriptor() ([]byte, []int) {
	return file_expression_types_proto_rawDescGZIP(), []int{10}
}

func (x *OOB) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

func (x *OOB) GetHTTP() string {
	if x != nil {
		return x.HTTP
	}
	return ""
}

func (x *OOB) GetDNS() string {
	if x != nil {
		return x.DNS
	}
	return ""
}

func (x *OOB) GetProtocolHTTP() string {
	if x != nil {
		return x.ProtocolHTTP
	}
	return ""
}

func (x *OOB) GetProtocolDNS() string {
	if x != nil {
		return x.ProtocolDNS
	}
	return ""
}

var File_expression_types_proto protoreflect.FileDescriptor

var file_expression_types_proto_rawDesc = []byte{
	0x0a, 0x16, 0x65, 0x78, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x2f, 0x74, 0x79, 0x70,
	0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x65, 0x78, 0x70, 0x72, 0x22, 0x50,
	0x0a, 0x08, 0x41, 0x64, 0x64, 0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x74, 0x72,
	0x61, 0x6e, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x74,
	0x72, 0x61, 0x6e, 0x73, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x64, 0x64, 0x72,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x61, 0x64, 0x64, 0x72, 0x12, 0x12, 0x0a, 0x04,
	0x70, 0x6f, 0x72, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74,
	0x22, 0x64, 0x0a, 0x08, 0x43, 0x6f, 0x6e, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x26, 0x0a, 0x06,
	0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x65,
	0x78, 0x70, 0x72, 0x2e, 0x41, 0x64, 0x64, 0x72, 0x54, 0x79, 0x70, 0x65, 0x52, 0x06, 0x73, 0x6f,
	0x75, 0x72, 0x63, 0x65, 0x12, 0x30, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x74, 0x69, 0x6e, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x65, 0x78, 0x70, 0x72,
	0x2e, 0x41, 0x64, 0x64, 0x72, 0x54, 0x79, 0x70, 0x65, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x74, 0x69,
	0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0xa7, 0x01, 0x0a, 0x07, 0x55, 0x72, 0x6c, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x06, 0x73, 0x63, 0x68, 0x65, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x6f,
	0x6d, 0x61, 0x69, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x6f, 0x6d, 0x61,
	0x69, 0x6e, 0x12, 0x12, 0x0a, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61,
	0x74, 0x68, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x12, 0x14,
	0x0a, 0x05, 0x71, 0x75, 0x65, 0x72, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x71,
	0x75, 0x65, 0x72, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x66, 0x72, 0x61, 0x67, 0x6d, 0x65, 0x6e, 0x74,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66, 0x72, 0x61, 0x67, 0x6d, 0x65, 0x6e, 0x74,
	0x22, 0x26, 0x0a, 0x12, 0x4e, 0x65, 0x74, 0x77, 0x6f, 0x72, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x61, 0x77, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x03, 0x72, 0x61, 0x77, 0x22, 0x4b, 0x0a, 0x13, 0x4e, 0x65, 0x74, 0x77,
	0x6f, 0x72, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x22, 0x0a, 0x04, 0x63, 0x6f, 0x6e, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e,
	0x65, 0x78, 0x70, 0x72, 0x2e, 0x43, 0x6f, 0x6e, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x63,
	0x6f, 0x6e, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x61, 0x77, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x03, 0x72, 0x61, 0x77, 0x22, 0x22, 0x0a, 0x0e, 0x53, 0x73, 0x68, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x61, 0x77, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x72, 0x61, 0x77, 0x22, 0xc5, 0x01, 0x0a, 0x0f, 0x53, 0x73,
	0x68, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x22, 0x0a,
	0x04, 0x63, 0x6f, 0x6e, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x65, 0x78,
	0x70, 0x72, 0x2e, 0x43, 0x6f, 0x6e, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x63, 0x6f, 0x6e,
	0x6e, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x61, 0x77, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03,
	0x72, 0x61, 0x77, 0x12, 0x3f, 0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x65, 0x78, 0x70, 0x72, 0x2e, 0x53, 0x73, 0x68,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x54, 0x79, 0x70, 0x65, 0x2e, 0x4d, 0x65, 0x74,
	0x61, 0x64, 0x61, 0x74, 0x61, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x08, 0x6d, 0x65, 0x74, 0x61,
	0x64, 0x61, 0x74, 0x61, 0x1a, 0x3b, 0x0a, 0x0d, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38,
	0x01, 0x22, 0x8d, 0x02, 0x0a, 0x0f, 0x48, 0x54, 0x54, 0x50, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1f, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x65, 0x78, 0x70, 0x72, 0x2e, 0x55, 0x72, 0x6c, 0x54, 0x79, 0x70,
	0x65, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x12, 0x3c,
	0x0a, 0x07, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x22, 0x2e, 0x65, 0x78, 0x70, 0x72, 0x2e, 0x48, 0x54, 0x54, 0x50, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x54, 0x79, 0x70, 0x65, 0x2e, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x52, 0x07, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x12, 0x21, 0x0a, 0x0c,
	0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0b, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x12, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x62,
	0x6f, 0x64, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x61, 0x77, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0c,
	0x52, 0x03, 0x72, 0x61, 0x77, 0x1a, 0x3a, 0x0a, 0x0c, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38,
	0x01, 0x22, 0xd8, 0x03, 0x0a, 0x10, 0x48, 0x54, 0x54, 0x50, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1f, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x65, 0x78, 0x70, 0x72, 0x2e, 0x55, 0x72, 0x6c, 0x54, 0x79,
	0x70, 0x65, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12,
	0x12, 0x0a, 0x04, 0x62, 0x6f, 0x64, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x62,
	0x6f, 0x64, 0x79, 0x12, 0x1f, 0x0a, 0x0b, 0x62, 0x6f, 0x64, 0x79, 0x5f, 0x73, 0x74, 0x72, 0x69,
	0x6e, 0x67, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x62, 0x6f, 0x64, 0x79, 0x53, 0x74,
	0x72, 0x69, 0x6e, 0x67, 0x12, 0x3d, 0x0a, 0x07, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x18,
	0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x23, 0x2e, 0x65, 0x78, 0x70, 0x72, 0x2e, 0x48, 0x54, 0x54,
	0x50, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x54, 0x79, 0x70, 0x65, 0x2e, 0x48, 0x65,
	0x61, 0x64, 0x65, 0x72, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x68, 0x65, 0x61, 0x64,
	0x65, 0x72, 0x73, 0x12, 0x21, 0x0a, 0x0c, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x5f, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x6f, 0x6e, 0x74, 0x65,
	0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6c, 0x61, 0x74, 0x65, 0x6e, 0x63,
	0x79, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x6c, 0x61, 0x74, 0x65, 0x6e, 0x63, 0x79,
	0x12, 0x10, 0x0a, 0x03, 0x72, 0x61, 0x77, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x03, 0x72,
	0x61, 0x77, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x74, 0x69, 0x74, 0x6c, 0x65, 0x12, 0x21, 0x0a, 0x0c, 0x74, 0x69, 0x74, 0x6c,
	0x65, 0x5f, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b,
	0x74, 0x69, 0x74, 0x6c, 0x65, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x12, 0x1d, 0x0a, 0x0a, 0x72,
	0x61, 0x77, 0x5f, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x09, 0x72, 0x61, 0x77, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x19, 0x0a, 0x08, 0x72, 0x61,
	0x77, 0x5f, 0x63, 0x65, 0x72, 0x74, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x07, 0x72, 0x61,
	0x77, 0x43, 0x65, 0x72, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x69, 0x63, 0x6f, 0x6e, 0x5f, 0x75, 0x72,
	0x6c, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x69, 0x63, 0x6f, 0x6e, 0x55, 0x72, 0x6c,
	0x1a, 0x3a, 0x0a, 0x0c, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b,
	0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0xde, 0x01, 0x0a,
	0x0b, 0x52, 0x65, 0x76, 0x65, 0x72, 0x73, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1f, 0x0a, 0x03,
	0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0d, 0x2e, 0x65, 0x78, 0x70, 0x72,
	0x2e, 0x55, 0x72, 0x6c, 0x54, 0x79, 0x70, 0x65, 0x52, 0x03, 0x75, 0x72, 0x6c, 0x12, 0x10, 0x0a,
	0x03, 0x72, 0x6d, 0x69, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x72, 0x6d, 0x69, 0x12,
	0x12, 0x0a, 0x04, 0x6c, 0x64, 0x61, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6c,
	0x64, 0x61, 0x70, 0x12, 0x12, 0x0a, 0x04, 0x66, 0x6c, 0x61, 0x67, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x66, 0x6c, 0x61, 0x67, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x6f, 0x6d, 0x61, 0x69,
	0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x12,
	0x0e, 0x0a, 0x02, 0x69, 0x70, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x70, 0x12,
	0x31, 0x0a, 0x15, 0x69, 0x73, 0x5f, 0x64, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x5f, 0x6e, 0x61, 0x6d,
	0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x18, 0x07, 0x20, 0x01, 0x28, 0x08, 0x52, 0x12,
	0x69, 0x73, 0x44, 0x6f, 0x6d, 0x61, 0x69, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x53, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x12, 0x19, 0x0a, 0x08, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x49, 0x64, 0x22, 0x89, 0x01,
	0x0a, 0x03, 0x4f, 0x4f, 0x42, 0x12, 0x16, 0x0a, 0x06, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x12, 0x0a,
	0x04, 0x48, 0x54, 0x54, 0x50, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x48, 0x54, 0x54,
	0x50, 0x12, 0x10, 0x0a, 0x03, 0x44, 0x4e, 0x53, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03,
	0x44, 0x4e, 0x53, 0x12, 0x22, 0x0a, 0x0c, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x48,
	0x54, 0x54, 0x50, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0x63, 0x6f, 0x6c, 0x48, 0x54, 0x54, 0x50, 0x12, 0x20, 0x0a, 0x0b, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0x63, 0x6f, 0x6c, 0x44, 0x4e, 0x53, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x50, 0x72,
	0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x44, 0x4e, 0x53, 0x42, 0x0e, 0x5a, 0x0c, 0x2e, 0x2f, 0x65,
	0x78, 0x70, 0x72, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_expression_types_proto_rawDescOnce sync.Once
	file_expression_types_proto_rawDescData = file_expression_types_proto_rawDesc
)

func file_expression_types_proto_rawDescGZIP() []byte {
	file_expression_types_proto_rawDescOnce.Do(func() {
		file_expression_types_proto_rawDescData = protoimpl.X.CompressGZIP(file_expression_types_proto_rawDescData)
	})
	return file_expression_types_proto_rawDescData
}

var file_expression_types_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_expression_types_proto_goTypes = []any{
	(*AddrType)(nil),            // 0: expr.AddrType
	(*ConnType)(nil),            // 1: expr.ConnType
	(*UrlType)(nil),             // 2: expr.UrlType
	(*NetworkRequestType)(nil),  // 3: expr.NetworkRequestType
	(*NetworkResponseType)(nil), // 4: expr.NetworkResponseType
	(*SshRequestType)(nil),      // 5: expr.SshRequestType
	(*SshResponseType)(nil),     // 6: expr.SshResponseType
	(*HTTPRequestType)(nil),     // 7: expr.HTTPRequestType
	(*HTTPResponseType)(nil),    // 8: expr.HTTPResponseType
	(*ReverseType)(nil),         // 9: expr.ReverseType
	(*OOB)(nil),                 // 10: expr.OOB
	nil,                         // 11: expr.SshResponseType.MetadataEntry
	nil,                         // 12: expr.HTTPRequestType.HeadersEntry
	nil,                         // 13: expr.HTTPResponseType.HeadersEntry
}
var file_expression_types_proto_depIdxs = []int32{
	0,  // 0: expr.ConnType.source:type_name -> expr.AddrType
	0,  // 1: expr.ConnType.destination:type_name -> expr.AddrType
	1,  // 2: expr.NetworkResponseType.conn:type_name -> expr.ConnType
	1,  // 3: expr.SshResponseType.conn:type_name -> expr.ConnType
	11, // 4: expr.SshResponseType.metadata:type_name -> expr.SshResponseType.MetadataEntry
	2,  // 5: expr.HTTPRequestType.url:type_name -> expr.UrlType
	12, // 6: expr.HTTPRequestType.headers:type_name -> expr.HTTPRequestType.HeadersEntry
	2,  // 7: expr.HTTPResponseType.url:type_name -> expr.UrlType
	13, // 8: expr.HTTPResponseType.headers:type_name -> expr.HTTPResponseType.HeadersEntry
	2,  // 9: expr.ReverseType.url:type_name -> expr.UrlType
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_expression_types_proto_init() }
func file_expression_types_proto_init() {
	if File_expression_types_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_expression_types_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*AddrType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_expression_types_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*ConnType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_expression_types_proto_msgTypes[2].Exporter = func(v any, i int) any {
			switch v := v.(*UrlType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_expression_types_proto_msgTypes[3].Exporter = func(v any, i int) any {
			switch v := v.(*NetworkRequestType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_expression_types_proto_msgTypes[4].Exporter = func(v any, i int) any {
			switch v := v.(*NetworkResponseType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_expression_types_proto_msgTypes[5].Exporter = func(v any, i int) any {
			switch v := v.(*SshRequestType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_expression_types_proto_msgTypes[6].Exporter = func(v any, i int) any {
			switch v := v.(*SshResponseType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_expression_types_proto_msgTypes[7].Exporter = func(v any, i int) any {
			switch v := v.(*HTTPRequestType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_expression_types_proto_msgTypes[8].Exporter = func(v any, i int) any {
			switch v := v.(*HTTPResponseType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_expression_types_proto_msgTypes[9].Exporter = func(v any, i int) any {
			switch v := v.(*ReverseType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_expression_types_proto_msgTypes[10].Exporter = func(v any, i int) any {
			switch v := v.(*OOB); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_expression_types_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_expression_types_proto_goTypes,
		DependencyIndexes: file_expression_types_proto_depIdxs,
		MessageInfos:      file_expression_types_proto_msgTypes,
	}.Build()
	File_expression_types_proto = out.File
	file_expression_types_proto_rawDesc = nil
	file_expression_types_proto_goTypes = nil
	file_expression_types_proto_depIdxs = nil
}
